[package]
name = "makepad-stitch-coremark"
version = "0.1.0"
edition = "2021"

[dependencies]
makepad-stitch = { path = ".." }
wasm3 = { version = "0.3.1", features = ["build-bindgen"] }
wasmi = "0.31.2"
wasmtime = "20.0.1"
